export const enum CALCULATION_ERROR_TYPE {
  INVALID_DATA = "INVALID_DATA",
  DUPLICATE_DATA = "DUPLICATE_DATA",
}

export const enum CALCULATION_DUPLICATION_ACTION_TYPE {
  KEEP_FIRST = "KEEP_FIRST",
  COMBINE_ALL = "COMBINE_ALL",
}
